empleado/applications/ventilcion/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from applications import ventilcion

   
urlpatterns = [

    path('registro/', views.registroventi.as_view(),name='registro'),
    path('listaprograma/', views.listaListView.as_view()), 
    path('cambiar/<pk>/', views.ProgramadateView.as_view(), name= 'cambiar'),
    path('listaprograma/', views.listaListView.as_view(), name= 'listaprograma' ),
    path('objetivo/', views.suma, name= 'objetivo' ),
    path('informe/', views.informe, name= 'informe' ),
    path('velocidad/', views.Velocidad, name= 'velocidad' ),
    path('guardar/', views.guardar, name= 'guardar' ),
    path('cargar/', views.cargar, name= 'cargar' ),
    path('flujo/', views.flujorequerido, name= 'flujo' ),
    path('indice/', views.indice, name= 'indice'),
    path('tutorial/', views.download_file, name= 'tutorial'),
    path('eliminar/<pk>/', views.ProgramaDeleteView.as_view(), name= 'eliminar'),

  
]

empleado/empleado/urls.py
from django.contrib import admin
from django.urls import path, re_path, include 
from django.urls import reverse

urlpatterns = [
    path('admin/', admin.site.urls),
    #incluimos los urls
   
    re_path('',include('applications.ventilcion.urls')),

    
]

empleado/applications/ventilcion/models.py
from django.db import models
from django.db.models.base import ModelStateFieldsCacheDescriptor
from  applications.areas.models import areaslista
from  applications.Union.models import tipounion
# Create your models here.

class Programa(models.Model): 

   Tramo = models.CharField('Tramo', max_length=50) 
   Dfinal= models.BooleanField('Derivación final',default=False)
   de1= models.CharField('Derivación 1', max_length=4,blank=True)
   de2= models.CharField('Derivación 2', max_length=4,blank=True)
   de3= models.CharField('Derivación 3', max_length=4,blank=True)
   d1distancia = models.FloatField('Distancia del tramo[m]',blank=True)
   Ntramo = models.IntegerField('Número de codos por tramo',null=True, blank=True)
   tipoarea =  models.ForeignKey(areaslista,null=True, blank=True, on_delete = models.CASCADE  )
   Codigo= models.CharField('Codigo', max_length=50,blank=True) 
   Darea = models.FloatField('área[m2]',max_length=4, null=True, blank=True)
   npersonas = models.IntegerField('Número de personas',null=True, blank=True)
   Unión = models.ForeignKey(tipounion,null=True, blank=True, on_delete = models.CASCADE  )

   def __str__(self):
        return "{}-{}-{}-{}-{}-{}".format (self.Tramo, self.Dfinal,self.de1, self.de2,self.de3,self.d1distancia,
         self. Ntramo,self. tipoarea, self.Codigo,self.Darea,self. npersonas, self.Unión )

empleado/applications/ventilcion/forms.py
from typing import Union
from django import forms


from django.contrib.admin.widgets import AutocompleteSelect
from django.contrib import admin
from  .models import Programa
from  applications.areas.models import areaslista



class ProgramaForm(forms.ModelForm):
   
    class Meta:
        model = Programa
        fields = (
            'Tramo',
            'Dfinal',
            'de1',
            'de2',
            'de3',
            'd1distancia',
            'Ntramo',
            'tipoarea',
            'Codigo',
            'Darea',
            'npersonas',
            'Unión',
        )
        labels = {
            'Tramo':'Tramo',
            'Dfinal':'Derivación final',
            'de1':'Derivación 1',
            'de2':'Derivación 2',
            'de3':'Derivación 3',
            'de1distancia':'Dinstacia del tramo',
            'Ntramo':'Número de codos por tramo',
            'tipoarea':'Tipo de área',
            'Codigo':'Código del área',
            'Darea':'Área [m2]',
            'npersonas':'Número de personas por area',
            'Unión':'Tipo de unión',

        } 


        widgets = {
            'Tramo':forms.TextInput(attrs={'class':'form-control','placeholder':'Ingrese el Tramo'}),
            'Dfinal':forms.CheckboxInput(attrs={'class':'form-control'}),
            'de1':forms.TextInput(attrs={'class':'form-control','placeholder':'Ingrese la derivación 1'}),
            'de2':forms.TextInput(attrs={'class':'form-control','placeholder':'Ingrese la derivación 2'}),
            'de3':forms.TextInput(attrs={'class':'form-control','placeholder':'Ingrese la Derivación 3'}),
            'd1distancia':forms.TextInput(attrs={'class':'form-control','placeholder':'Ingrese la distancia en [m]'}),
            'Ntramo':forms.TextInput(attrs={'class':'form-control'}),
            'tipoarea':forms.Select(attrs={'class':'form-control'}),
            'Codigo':forms.TextInput(attrs={'class':'form-control'}),
            'Darea':forms.TextInput(attrs={'class':'form-control','placeholder':'Ingrese el área [m2]'}),
            'npersonas':forms.TextInput(attrs={'class':'form-control'}),
            'Unión':forms.Select(attrs={'class':'form-control'}),

        }





    
  

empleado/applications/ventilcion/views.py
from django.core.exceptions import RequestAborted
from django.db.models import query
from django.db.models.query import QuerySet
from django.forms.models import fields_for_model
from django.http import request
from django.shortcuts import render, redirect
from django.urls.base import is_valid_path
from django.views.generic import (TemplateView, 
ListView, UpdateView,DeleteView,
CreateView
)
from .models import Programa
from openpyxl import Workbook
from  applications.areas.models import areaslista
from django.http import HttpResponse, Http404
from .forms import ProgramaForm

from django.http import StreamingHttpResponse
 
from django.core.files import File
from django.urls import reverse_lazy
import pandas as pd
from pandas import ExcelWriter
import openpyxl
import numpy as np 
import os.path
from tablib import Dataset
os.environ.setdefault("DJANGO_SETTINGS","empledo.settings")
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "StreamingHttpResponse.settings")
 

# Create your views here.

def programa_edit(request,id_Programa):
    programa=Programa.objects.get(id=id_Programa)
    if request.method== 'GET':
        form = ProgramaForm(instance=programa)
    else:
        form= ProgramaForm(request.POST,instance=programa)
        if form.is_valid():
            form.save()
        return redirect('ventilcion:listaprograma')
    return render(request, 'ventilcion/programaventi.html', {'form':form})


class registroventi(CreateView):
    model = Programa
    template_name = "ventilcion/programaventi.html"
    form_class= ProgramaForm
    success_url = '.'
  

class listaListView(ListView):
    model = Programa
    template_name = "ventilcion/listaventi.html"

    
class ProgramadateView(UpdateView):
    template_name = "ventilcion/editar.html"
    model = Programa
    form_class=ProgramaForm
    success_url='.'


class ProgramaDeleteView(DeleteView):
    model = Programa
    template_name = "ventilcion/eliminard.html"
    success_url= reverse_lazy('listaprograma')


def suma(request):
    qs=Programa.objects.all().values()
    data = pd.DataFrame(qs)
    data = data.fillna(0)
    data = data.fillna({'de1':'x'})
    qs1=areaslista.objects.all().values()
    data1 = pd.DataFrame(qs1)
   




    data ['flujo']=0
    data ['D.equivalente']=0
    data ['lado1']=0
    data ['lado2']=0
    data ['velocidad']=0
    data ['D.real']=0
    data ['Perdidas por longitud']=0
    data ['Perdidas acumulada']=0
    data ['Recinto']=0
    qs2=[0]
    data2=pd.DataFrame(qs2,columns=['d.principal'])
    qs3=[0]
    data3=pd.DataFrame(qs3,columns=['Caída de presión  del sistema de ventilación [Pa]'])
    qs4=[0]
    data4=pd.DataFrame(qs4,columns=['Pérdidas por longitud [Pa/m]'])
    qs5=[0]
    data5=pd.DataFrame(qs5,columns=['Tramo'])


    


    

   #llenado la columna de flujo 
   # flujo requerido por cada region
    for i in range(0,len(data)):
        if data.loc[i,'Dfinal']==True:
            for x in range(0,len(data1)):
                if data.loc[i,'tipoarea_id']>=1 and data.loc[i,'tipoarea_id']<=48 :
                    if data.loc[i,'tipoarea_id']== data1.loc[x,'id']:
                        resul=data.loc[i,'Darea']*data1.loc[x,'litrosporarea']+data.loc[i,'npersonas']*data1.loc[x,'listrosporpersona']
                        data.loc[i,'flujo']=resul
                        data.loc[i,'Recinto']=data1.loc[x,'areas']
                        
                        
                elif data.loc[i,'tipoarea_id']>=56:
                    if data.loc[i,'tipoarea_id']== data1.loc[x,'id']:
                        resul=(data.loc[i,'Darea']*data1.loc[x,'litrosporarea']*3.5)/3.6
                        data.loc[i,'flujo']=resul
                        data.loc[i,'Recinto']=data1.loc[x,'areas']



                
                    
        else:
            resul=0
            data.loc[i,'flujo']=resul
    
   #flujo por cada tramo 
    r=False   
    while r==False:
        r=True
        for y in range(0,len(data)):
            if data.loc[y,'flujo']==0:
                if data.loc[y,'de3']=='':
                    for l in range(0,len(data)):
                        if data.loc[y,'de1']==data.loc[l,'Tramo'] and data.loc[l,'flujo']!=0:
                            if data.loc[y,'Unión_id']!=4:
                                for p in range(0,len(data)):
                                    if data.loc[y,'de2']==data.loc[p,'Tramo'] and data.loc[p,'flujo']!=0:
                                         data.loc[y,'flujo']=data.loc[l,'flujo']+data.loc[p,'flujo']
                            elif data.loc[y,'Unión_id']==4:
                                for x in range(0,len(data1)):
                                    if data.loc[y,'tipoarea_id']>=1 and data.loc[y,'tipoarea_id']<=48 :
                                        if data.loc[y,'tipoarea_id']== data1.loc[x,'id']:
                                            resul=data.loc[y,'Darea']*data1.loc[x,'litrosporarea']+data.loc[y,'npersonas']*data1.loc[x,'listrosporpersona']
                                            data.loc[y,'Recinto']=data1.loc[x,'areas']
                                    elif data.loc[y,'tipoarea_id']>=56:
                                        if data.loc[y,'tipoarea_id']== data1.loc[x,'id']:
                                           resul=(data.loc[y,'Darea']*data1.loc[x,'litrosporarea']*3.5)/3.6
                                           data.loc[y,'Recinto']=data1.loc[x,'areas']
                                data.loc[y,'flujo']=data.loc[l,'flujo']+resul

                if data.loc[y,'de3']!='':
                    for l in range(0,len(data)):
                        if data.loc[y,'de1']==data.loc[l,'Tramo'] and data.loc[l,'flujo']!=0:
                            for p in range(0,len(data)):
                                if data.loc[y,'de2']==data.loc[p,'Tramo'] and data.loc[p,'flujo']!=0:
                                   for w in range(0,len(data)):
                                       if data.loc[y,'de3']==data.loc[w,'Tramo'] and data.loc[w,'flujo']!=0:
                                          data.loc[y,'flujo']=data.loc[l,'flujo']+data.loc[p,'flujo']+data.loc[w,'flujo']

        for y in range(0,len(data)):
            if data.loc[y,'flujo']==0:
                r=False
    
    

    # diámetro equivalente 
   
    ve=float(request.POST.get('num1'))

   
    
    Dh = np.sqrt(((data["flujo"].max()/1000)/ve)*(4/3.1415))
    de=1.2 #densidad del aire
    Re=(de*Dh*ve)/0.000018 #Reynolds
    e1=0.1219     #rugosidad
    Rr=e1/(Dh*1000)     #rugosidad relativa
    REs= friccion(Re,Rr)    #factor de fricion 
    Pl=REs*((de*np.square(ve))/(2*Dh))
 
    #diametro equivalente 
    for i in range(0,len(data)):
        Y=de*0.8105*np.square((data.loc[i,'flujo']/1000))
        P=(de*4*(data.loc[i,'flujo']/1000))/(0.000024*3.1415)
        Dequi=Dequivalente(Y,P,Pl,e1)
        data.loc[i,'D.equivalente']=Dequi*1000 #transformar a mm

    #selecionar diametros  y velocidad real
    for i in range(0,len(data)):
        x1=data.loc[i,'D.equivalente']
        if x1<(ductos['du'][0]):
            data.loc[i,'lado1']=(ductos['lmayor'][0])
            data.loc[i,'lado2']=(ductos['lmenor'][0])
            data.loc[i,'velocidad']=((data.loc[i,'flujo'])/1000)/(ductos['area'][0])
            data.loc [i,'D.real']=ductos['du'][0]
        else:
            for y in range(0,26):
                x2=(ductos['du'][y])
                x3=(ductos['du'][y+1])
                if x1 >= x2 and x1<x3:
                    x4=((x3-x2)/2)+x2
                   
                    if x1 < x4:
                        #print(y)
                        data.loc[i,'lado1']=(ductos['lmayor'][y])
                        data.loc[i,'lado2']=(ductos['lmenor'][y])
                        velo=(ductos['area'][y])
                        data.loc[i,'velocidad']=((data.loc[i,'flujo'])/1000)/velo
                        data.loc [i,'D.real']=ductos['du'][y]
                    elif x1 > x4:
                        #print(y+1)
                        data.loc[i,'lado1']=(ductos['lmayor'][y+1])
                        data.loc[i,'lado2']=(ductos['lmenor'][y+1])
                        velo=(ductos['area'][y+1])
                        data.loc[i,'velocidad']=((data.loc[i,'flujo'])/1000)/velo
                        data.loc [i,'D.real']=ductos['du'][y+1]
    
    #perdidas por longuitud.
 
    for i in range(0,len(data)):
        Rrre=e1/(data.loc [i,'D.real'])
        Rere=(de*((data.loc [i,'D.real'])/1000)*data.loc[i,'velocidad'])/0.000024
        Resre=friccion(Rere,Rrre)

        Plre=Resre*(de*np.square(data.loc[i,'velocidad']))/(2*(data.loc [i,'D.real'])/1000)
        data.loc[i,'Factor de pérdida']=Plre
        #perdidas por codos.
        Pc=7*data.loc[i,'lado2']*data.loc[i,'Ntramo']/1000
        Plre=Plre*(data.loc[i,'d1distancia']+Pc)
        data.loc[i,'Perdidas por longitud']=Plre
   
 #perdida acumulada 
    for i in range(0,len(data)):
        if data.loc[i,'Dfinal']==True:
            data.loc[i,'Perdidas acumulada']=data.loc[i,'Perdidas por longitud']
            
        else:
            resul=0
            data.loc[i,'Perdidas acumulada']=resul

    
    r=False   
    while r==False:
        r=True
        for y in range(0,len(data)):
            if data.loc[y,'Perdidas acumulada']==0:
               
                if data.loc[y,'de3']=='':
                    for l in range(0,len(data)):
                        
                        if data.loc[y,'de1']==data.loc[l,'Tramo'] and data.loc[l,'Perdidas acumulada']!=0:
                            if data.loc[y,'Unión_id']!=4:

                                for p in range(0,len(data)):
                                   if data.loc[y,'de2']==data.loc[p,'Tramo'] and data.loc[p,'Perdidas acumulada']!=0:
                                        
                                        data.loc[y,'Perdidas acumulada']=data.loc[l,'Perdidas acumulada']+data.loc[p,'Perdidas acumulada']+data.loc[y,'Perdidas por longitud']

empleado/templates/ventilcion/cargar.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />
    <style>

        body{
            margin: 20px 20px 20px 20px;
        }

        .form-control {
            border-radius: 0;
            box-shadow: none;
            border-color: #d2d6de
        }

        .select2-hidden-accessible {
            border: 0 !important;
            clip: rect(0 0 0 0) !important;
            height: 1px !important;
            margin: -1px !important;
            overflow: hidden !important;
            padding: 0 !important;
            position: absolute !important;
            width: 1px !important
        }

        .form-control {
            display: block;
            width: 100%;
            height: 34px;
            padding: 6px 12px;
            font-size: 14px;
            line-height: 1.42857143;
            color: #555;
            background-color: #fff;
            background-image: none;
            border: 1px solid #ccc;
            border-radius: 4px;
            -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, .075);
            box-shadow: inset 0 1px 1px rgba(0, 0, 0, .075);
            -webkit-transition: border-color ease-in-out .15s, -webkit-box-shadow ease-in-out .15s;
            -o-transition: border-color ease-in-out .15s, box-shadow ease-in-out .15s;
            transition: border-color ease-in-out .15s, box-shadow ease-in-out .15s
        }

        .select2-container--default .select2-selection--single,
        .select2-selection .select2-selection--single {
            border: 1px solid #d2d6de;
            border-radius: 0;
            padding: 6px 12px;
            height: 34px
        }

        .select2-container--default .select2-selection--single {
            background-color: #fff;
            border: 1px solid #aaa;
            border-radius: 4px
        }

        .select2-container .select2-selection--single {
            box-sizing: border-box;
            cursor: pointer;
            display: block;
            height: 28px;
            user-select: none;
            -webkit-user-select: none
        }

        .select2-container .select2-selection--single .select2-selection__rendered {
            padding-right: 10px
        }

        .select2-container .select2-selection--single .select2-selection__rendered {
            padding-left: 0;
            padding-right: 0;
            height: auto;
            margin-top: -3px
        }

        .select2-container--default .select2-selection--single .select2-selection__rendered {
            color: #444;
            line-height: 28px
        }

        .select2-container--default .select2-selection--single,
        .select2-selection .select2-selection--single {
            border: 1px solid #d2d6de;
            border-radius: 0 !important;
            padding: 6px 12px;
            height: 40px !important
        }

        .select2-container--default .select2-selection--single .select2-selection__arrow {
            height: 26px;
            position: absolute;
            top: 6px !important;
            right: 1px;
            width: 20px
        }
    </style>

    <script>
        $(document).ready(function() { 
            $('#divarea,#divtipoarea,#divcodigoarea').hide();

            $('.select2').select2({
                closeOnSelect: false
            });
            
            $('#id_Dfinal').click(function(){
                if ($('#id_Dfinal').is(":checked")){
                    $('#divarea,#divtipoarea,#divcodigoarea').show();
                }else

                {
                    $('#divarea,#divtipoarea,#divcodigoarea').hide();
                }
            });

        });
    </script>



</head>
<body>
<div class="alert alert-primary" role="alert">
    <center><h1>Escuela Politécnica Nacional</h1></center>
    <center><h2>Aplicación para sistemas de ventilación mecánica</h2></center>
</div>
<hr>
<hr>
<body>
    <div class=" row">
        <div class=" col -12">
            <form method="post" enctype="multipart/form-data" action="{% url 'cargar' %} " method="post" >{% csrf_token %}
                <div class="form-group row">
                    <label for="Tramo" class="col-sm-5 col-form-label"><b>Nombre del archivo</b></label>
                    <div class="col-sm-5">
                        <input type="file" name="file">
                    </div>
                </div>
                <button type="submit" class="btn btn-primary" >cargar</button> 
                <hr>
                <a class="boton btn btn-info" href="{% url 'listaprograma' %} "class="btn btn-warning">Datos</a>
                <hr>
            </form>
        </div>
    </div>
   

    
</body>
</html>

empleado/templates/ventilcion/editar.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />
    <style>

        body{
            margin: 20px 20px 20px 20px;
        }

        .form-control {
            border-radius: 0;
            box-shadow: none;
            border-color: #d2d6de
        }

        .select2-hidden-accessible {
            border: 0 !important;
            clip: rect(0 0 0 0) !important;
            height: 1px !important;
            margin: -1px !important;
            overflow: hidden !important;
            padding: 0 !important;
            position: absolute !important;
            width: 1px !important
        }

        .form-control {
            display: block;
            width: 100%;
            height: 34px;
            padding: 6px 12px;
            font-size: 14px;
            line-height: 1.42857143;
            color: #555;
            background-color: #fff;
            background-image: none;
            border: 1px solid #ccc;
            border-radius: 4px;
            -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, .075);
            box-shadow: inset 0 1px 1px rgba(0, 0, 0, .075);
            -webkit-transition: border-color ease-in-out .15s, -webkit-box-shadow ease-in-out .15s;
            -o-transition: border-color ease-in-out .15s, box-shadow ease-in-out .15s;
            transition: border-color ease-in-out .15s, box-shadow ease-in-out .15s
        }

        .select2-container--default .select2-selection--single,
        .select2-selection .select2-selection--single {
            border: 1px solid #d2d6de;
            border-radius: 0;
            padding: 6px 12px;
            height: 34px
        }

        .select2-container--default .select2-selection--single {
            background-color: #fff;
            border: 1px solid #aaa;
            border-radius: 4px
        }

        .select2-container .select2-selection--single {
            box-sizing: border-box;
            cursor: pointer;
            display: block;
            height: 28px;
            user-select: none;
            -webkit-user-select: none
        }

        .select2-container .select2-selection--single .select2-selection__rendered {
            padding-right: 10px
        }

        .select2-container .select2-selection--single .select2-selection__rendered {
            padding-left: 0;
            padding-right: 0;
            height: auto;
            margin-top: -3px
        }

        .select2-container--default .select2-selection--single .select2-selection__rendered {
            color: #444;
            line-height: 28px
        }

        .select2-container--default .select2-selection--single,
        .select2-selection .select2-selection--single {
            border: 1px solid #d2d6de;
            border-radius: 0 !important;
            padding: 6px 12px;
            height: 40px !important
        }

        .select2-container--default .select2-selection--single .select2-selection__arrow {
            height: 26px;
            position: absolute;
            top: 6px !important;
            right: 1px;
            width: 20px
        }
    </style>

    <script>
        $(document).ready(function() { 
            $('#de1,#de2,#de3,#tu').show();

            $('.select2').select2({
                closeOnSelect: false
            });
            
            $('#id_Dfinal').click(function(){
                if ($('#id_Dfinal').is(":checked")){
                    $('#de1,#de2,#de3,#tu').hide();
                }else
                
                {
                    $('#de1,#de2,#de3,#tu').show();
                }
            });

        });
    </script>



</head>
<body>
<div class="alert alert-primary" role="alert">
    <center><h1>Escuela Politécnica Nacional</h1></center>
    <center><h2>Aplicación para sistemas de ventilación mecánica</h2></center>
</div>
<form method="post">{% csrf_token %}

    <div class="form-group row">
        <label for="Tramo" class="col-sm-2 col-form-label"><b>Tramo</b></label>
        <div class="col-sm-9">
            {{form.Tramo}}
        </div>
    </div>
    <hr>
    <div class="form-group row">
        <div class="col-sm-2"><b>Derivación final</div>
        <div class="col-sm-9">
            {{form.Dfinal}}
            <div class="custom-control custom-checkbox">
            </div>
        </div>
    </div>
    <hr>

    <div class="form-group row" id="de1">
        <label for="derivacion1" class="col-sm-2 col-form-label"><b>Derivación 1</b></label>
        <div class="col-sm-9">
            {{form.de1}}
        </div>
    </div>

    <hr>

    <div class="form-group row" id="de2">
        <label for="derivacion2" class="col-sm-2 col-form-label"><b>Derivación 2</b></label>
        <div class="col-sm-9">
            {{form.de2}}
        </div>
    </div>

    <hr>
    <div class="form-group row"id="de3">
        <label for="derivacion3" class="col-sm-2 col-form-label"><b>Derivación 3</b></label>
        <div class="col-sm-9">
            {{form.de3}}
        </div>
    </div>

    <hr>
    <div class="form-group row">
        <label for="distancia" class="col-sm-2 col-form-label"><b>Distancia del Tramo</b></label>
        <div class="col-sm-9">
            {{form.d1distancia}}
        </div>
    </div>

    <hr>
    <div class="form-group row">
        <label for="codos" class="col-sm-2 col-form-label"><b>Número de codos por tramo</b></label>
        <div class="col-sm-9">
            {{form.Ntramo}}
        </div>
    </div>

    <hr>
    <div class="form-group row" id="divtipoarea">
        <label for="tipo" class="col-sm-2 col-form-label"><b>Tipo de Área</b></label>
        <div class="col-sm-9">
            <select class="form-control select2 select2-hidden-accessible" style="width: 100%;" tabindex="-1" aria-hidden="true" selected={{form.tipoarea}}
        </div>
    </div>

    <hr>
    <div class="form-group row" id="divcodigoarea">
        <label for="codigo" class="col-sm-2 col-form-label"><b>Código del Área</b></label>
        <div class="col-sm-9">
            {{form.Codigo}}
        </div>
    </div>

    <hr>
    <div class="form-group row" id="divarea">
        <label for="area" class="col-sm-2 col-form-label"><b>Área[m2]</b></label>
        <div class="col-sm-9">
            {{form.Darea}}
        </div>
    </div>

    <hr>

    <div class="form-group row" id="id_npersonas">
        <label for="personas" class="col-sm-2 col-form-label"><b>Número de personas por área</b></label>
        <div class="col-sm-9">
            {{form.npersonas}}
        </div>
    </div>

    <hr>
    <div class="form-group row"id="tu">
        <label for="union" class="col-sm-2 col-form-label"><b>Tipo de unión</b></label>
        <div class="col-sm-9">
            {{form.Unión}}
            </select>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-12">
            <center>
                <button type="submit" class="btn btn-primary">Cambiar</button>
                <a class="boton btn btn-info" href="{% url 'listaprograma' %} "class="btn btn-warning">Datos</a>
            </center>
        </div>
    </div>
</form>
</body>
</html>

<div class="alert alert-primary" role="alert">
    <center><h1>Escuela Politécnica Nacional</h1></center>
</div>

empleado/templates/ventilcion/result.html
<h1>resultado</h1>